
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 5/2/2015 5:37:24 PM
// Last Updated on: 

using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using Microsoft.Practices.EnterpriseLibrary.Data;
using EPay.DataClasses;
namespace EPay.DataAccess
{		
	public partial class MESSAGES_COMPANIEDA
	{
		public bool IsDirty {get; set;}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public List<MESSAGES_COMPANIEDC> LoadAll(DBConnection Connection)
		{
			List<MESSAGES_COMPANIEDC> objMESSAGES_COMPANIE = new List<MESSAGES_COMPANIEDC>();
			StringBuilder sql = new StringBuilder();
			sql.Append("proc_MESSAGES_COMPANIESLoadAll");

			DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
 
 
            DataSet ds = new DataSet();
			
			if (Connection.Transaction != null)
				ds = Connection.dataBase.ExecuteDataSet(dbCommandWrapper.DBCommand, Connection.Transaction);
			else
				ds = Connection.dataBase.ExecuteDataSet(dbCommandWrapper.DBCommand);
			
			  foreach (DataRow drRow in ds.Tables[0].Rows)
                {
				objMESSAGES_COMPANIE.Add(FillObject(drRow));
				}
				
            return objMESSAGES_COMPANIE;
		}
		
		public MESSAGES_COMPANIEDC LoadByPrimaryKey(DBConnection Connection, int MESSAGE_COMPANY_ID)
		{
			MESSAGES_COMPANIEDC objMESSAGES_COMPANIE = new MESSAGES_COMPANIEDC();
			StringBuilder sql = new StringBuilder();
			sql.Append("proc_MESSAGES_COMPANIESLoadByPrimaryKey");

			DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
						dbCommandWrapper.AddInParameter("p_MESSAGE_COMPANY_ID", DbType.Int32, MESSAGE_COMPANY_ID);
 				

			IDataReader reader = null;

			if (Connection.Transaction != null)
				reader = Connection.dataBase.ExecuteReader(dbCommandWrapper.DBCommand, Connection.Transaction);
			else
				reader = Connection.dataBase.ExecuteReader(dbCommandWrapper.DBCommand);

			objMESSAGES_COMPANIE = FillObject(reader);
            return objMESSAGES_COMPANIE;
		}
		public int Update(DBConnection Connection, List<MESSAGES_COMPANIEDC> objMESSAGES_COMPANIEs)        
        {
            int updatedCount = 0;
            foreach (MESSAGES_COMPANIEDC objMESSAGES_COMPANIE in objMESSAGES_COMPANIEs)
            {
                updatedCount = Update(Connection, objMESSAGES_COMPANIE);
            }
            return updatedCount;
        }
		private int Update(DBConnection Connection, MESSAGES_COMPANIEDC objMESSAGES_COMPANIE)
        {
            int updateCount = 0;

            StringBuilder sql = new StringBuilder();
            sql.Append("proc_MESSAGES_COMPANIESUpdate");

            DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
			
            
			dbCommandWrapper.AddInParameter("p_MESSAGE_COMPANY_ID", DbType.Int32, objMESSAGES_COMPANIE.MESSAGE_COMPANY_ID);
			dbCommandWrapper.AddInParameter("p_MESSAGE_ID", DbType.Int32, objMESSAGES_COMPANIE.MESSAGE_ID);
			dbCommandWrapper.AddInParameter("p_COMPANY_ID", DbType.Int32, objMESSAGES_COMPANIE.COMPANY_ID);
			dbCommandWrapper.AddInParameter("p_CREATED_ON", DbType.DateTime, objMESSAGES_COMPANIE.CREATED_ON);
			dbCommandWrapper.AddInParameter("p_CREATED_BY", DbType.Int32, objMESSAGES_COMPANIE.CREATED_BY);
			dbCommandWrapper.AddInParameter("p_MODIFIED_ON", DbType.DateTime, objMESSAGES_COMPANIE.MODIFIED_ON);
			dbCommandWrapper.AddInParameter("p_MODIFIED_BY", DbType.Int32, objMESSAGES_COMPANIE.MODIFIED_BY);
			dbCommandWrapper.AddInParameter("p_LOCK_COUNTER", DbType.Int32, objMESSAGES_COMPANIE.LOCK_COUNTER);


            if (Connection.Transaction != null)
                updateCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                updateCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand);
			
			if (updateCount == 0)
                objMESSAGES_COMPANIE.IsDirty = IsDirty = true;
            
			return updateCount;
        }
		public int Insert(DBConnection Connection, List<MESSAGES_COMPANIEDC> objMESSAGES_COMPANIEs)        
        {
            int insertCount = 0;
            foreach (MESSAGES_COMPANIEDC objMESSAGES_COMPANIE in objMESSAGES_COMPANIEs)
            {
                 insertCount = Insert(Connection, objMESSAGES_COMPANIE);
            }
            return  insertCount;
        }
		private int Insert(DBConnection Connection, MESSAGES_COMPANIEDC objMESSAGES_COMPANIE)
        {
            int insertCount = 0;

            StringBuilder sql = new StringBuilder();
            sql.Append("proc_MESSAGES_COMPANIESInsert");

            DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
			
            
			dbCommandWrapper.AddInParameter("p_MESSAGE_COMPANY_ID", DbType.Int32, objMESSAGES_COMPANIE.MESSAGE_COMPANY_ID);
			dbCommandWrapper.AddInParameter("p_MESSAGE_ID", DbType.Int32, objMESSAGES_COMPANIE.MESSAGE_ID);
			dbCommandWrapper.AddInParameter("p_COMPANY_ID", DbType.Int32, objMESSAGES_COMPANIE.COMPANY_ID);

            if (Connection.Transaction != null)
                insertCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                insertCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand);

            return insertCount;
        }
		public int Delete(DBConnection Connection, List<MESSAGES_COMPANIEDC> objMESSAGES_COMPANIEs)        
        {
            int deleteCount = 0;
            foreach (MESSAGES_COMPANIEDC objMESSAGES_COMPANIE in objMESSAGES_COMPANIEs)
            {
                 deleteCount = Delete(Connection, objMESSAGES_COMPANIE);
            }
            return  deleteCount;
        }
		private int Delete(DBConnection Connection, MESSAGES_COMPANIEDC objMESSAGES_COMPANIE)
        {
            int deleteCount = 0;

            StringBuilder sql = new StringBuilder();
            sql.Append("proc_MESSAGES_COMPANIESDelete");

            DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
            
			dbCommandWrapper.AddInParameter("p_MESSAGE_COMPANY_ID", DbType.Int32, objMESSAGES_COMPANIE.MESSAGE_COMPANY_ID);

            if (Connection.Transaction != null)
                deleteCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                deleteCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand);

            return deleteCount;
        }
		private MESSAGES_COMPANIEDC FillObject(IDataReader reader)
        {
			MESSAGES_COMPANIEDC objMESSAGES_COMPANIE = null;
            if (reader != null && reader.Read())
            {	
				objMESSAGES_COMPANIE = new MESSAGES_COMPANIEDC();
				objMESSAGES_COMPANIE.MESSAGE_COMPANY_ID = (int)reader["MESSAGE_COMPANY_ID"];
				objMESSAGES_COMPANIE.MESSAGE_ID = (int)reader["MESSAGE_ID"];
				objMESSAGES_COMPANIE.COMPANY_ID = (int)reader["COMPANY_ID"];
				objMESSAGES_COMPANIE.CREATED_ON = (DateTime)reader["CREATED_ON"];
				objMESSAGES_COMPANIE.CREATED_BY = (int)reader["CREATED_BY"];
				objMESSAGES_COMPANIE.MODIFIED_ON = (DateTime)reader["MODIFIED_ON"];
				objMESSAGES_COMPANIE.MODIFIED_BY = (int)reader["MODIFIED_BY"];
				objMESSAGES_COMPANIE.LOCK_COUNTER = reader["LOCK_COUNTER"] == DBNull.Value ? null : (int?)reader["LOCK_COUNTER"];

                reader.Close();
                reader.Dispose();
            }
            return objMESSAGES_COMPANIE;
        }
		private MESSAGES_COMPANIEDC FillObject(DataRow row)
        {
			MESSAGES_COMPANIEDC objMESSAGES_COMPANIE = null;
			objMESSAGES_COMPANIE = new MESSAGES_COMPANIEDC();
			objMESSAGES_COMPANIE.MESSAGE_COMPANY_ID = (int)row["MESSAGE_COMPANY_ID"];
			objMESSAGES_COMPANIE.MESSAGE_ID = (int)row["MESSAGE_ID"];
			objMESSAGES_COMPANIE.COMPANY_ID = (int)row["COMPANY_ID"];
			objMESSAGES_COMPANIE.CREATED_ON = (DateTime)row["CREATED_ON"];
			objMESSAGES_COMPANIE.CREATED_BY = (int)row["CREATED_BY"];
			objMESSAGES_COMPANIE.MODIFIED_ON = (DateTime)row["MODIFIED_ON"];
			objMESSAGES_COMPANIE.MODIFIED_BY = (int)row["MODIFIED_BY"];
			objMESSAGES_COMPANIE.LOCK_COUNTER = row["LOCK_COUNTER"] == DBNull.Value ? null : (int?)row["LOCK_COUNTER"];

            return objMESSAGES_COMPANIE;
        }
	}
}
