
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 2/23/2017 2:54:14 PM
// Last Updated on: 

using System;
using System.Collections.Generic;
using EPay.DataAccess;
using EPay.DataClasses;
using EPay.DataAccess;
using NMART.DataAccess;


namespace EPay.BusinessLayer
{
    public class PayDesignationBL
    {
        public bool IsDirty { get; set; }

        public List<PayDesignationDC> LoadAll()
        {
            DBConnection objConnection = new DBConnection();

            PayDesignationDA objPayDesignationDA = new PayDesignationDA();
            List<PayDesignationDC> objPayDesignationDC = null;
            try
            {
                objConnection.Open(false);
                objPayDesignationDC = objPayDesignationDA.LoadAll(objConnection);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return objPayDesignationDC;
        }


        public PayDesignationDC LoadByPrimaryKey(string Code)
        {
            DBConnection objConnection = new DBConnection();
            PayDesignationDA objPayDesignationDA = new PayDesignationDA();
            PayDesignationDC objPayDesignationDC = null;
            try
            {
                objConnection.Open(false);
                objPayDesignationDC = objPayDesignationDA.LoadByPrimaryKey(objConnection, Code);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return objPayDesignationDC;
        }
        public int Update(List<PayDesignationDC> objPayDesignations)
        {
            int updatedCount = 0;
            DBConnection objConnection = new DBConnection();
            PayDesignationDA objPayDesignationDA = new PayDesignationDA();
            try
            {
                objConnection.Open(true);
                updatedCount = objPayDesignationDA.Update(objConnection, objPayDesignations);
                IsDirty = objPayDesignationDA.IsDirty;
                if (IsDirty)
                    objConnection.Rollback();
                else
                    objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return updatedCount;
        }
        public int Insert(List<PayDesignationDC> objPayDesignations)
        {
            int insertedCount = 0;
            DBConnection objConnection = new DBConnection();
            PayDesignationDA objPayDesignationDA = new PayDesignationDA();
            try
            {
                objConnection.Open(true);
                insertedCount = objPayDesignationDA.Insert(objConnection, objPayDesignations);
                objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return insertedCount;
        }
        public int Delete(List<PayDesignationDC> objPayDesignations)
        {
            int deletedCount = 0;
            DBConnection objConnection = new DBConnection();
            PayDesignationDA objPayDesignationDA = new PayDesignationDA();
            try
            {
                objConnection.Open(true);
                deletedCount = objPayDesignationDA.Delete(objConnection, objPayDesignations);
                objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return deletedCount;
        }


    }
}
