
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 2/23/2017 2:54:14 PM
// Last Updated on: 

using System;
using System.Collections.Generic;
using EPay.DataAccess;
using EPay.DataClasses;
using EPay.DataAccess;
using NMART.DataAccess;


namespace EPay.BusinessLayer
{
    public class PaySalaryEditingBL
    {
        public bool IsDirty { get; set; }

        public List<PaySalaryEditingDC> LoadAllEmployee(int Month, int Year)
        {
            DBConnection objConnection = new DBConnection();

            PaySalaryEditingDA objPaySalaryEditingDA = new PaySalaryEditingDA();
            List<PaySalaryEditingDC> objPaySalaryEditingDC = null;
            try
            {
                objConnection.Open(false);
                objPaySalaryEditingDC = objPaySalaryEditingDA.LoadAllEmployee(objConnection, Month,Year);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                objConnection.Close();

            }
            return objPaySalaryEditingDC;
        }
        public List<PaySalaryEditingDC> LoadAll()
        {
            DBConnection objConnection = new DBConnection();

            PaySalaryEditingDA objPaySalaryEditingDA = new PaySalaryEditingDA();
            List<PaySalaryEditingDC> objPaySalaryEditingDC = null;
            try
            {
                objConnection.Open(false);
                objPaySalaryEditingDC = objPaySalaryEditingDA.LoadAll(objConnection);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return objPaySalaryEditingDC;
        }


        public PaySalaryEditingDC LoadByPrimaryKey(string ID)
        {
            DBConnection objConnection = new DBConnection();
            PaySalaryEditingDA objPaySalaryEditingDA = new PaySalaryEditingDA();
            PaySalaryEditingDC objPaySalaryEditingDC = null;
            try
            {
                objConnection.Open(false);
                objPaySalaryEditingDC = objPaySalaryEditingDA.LoadByPrimaryKey(objConnection, ID);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return objPaySalaryEditingDC;
        }
        public int Update(List<PaySalaryEditingDC> objPayDesignations)
        {
            int updatedCount = 0;
            DBConnection objConnection = new DBConnection();
            PaySalaryEditingDA objPaySalaryEditingDA = new PaySalaryEditingDA();
            try
            {
                objConnection.Open(true);
                updatedCount = objPaySalaryEditingDA.Update(objConnection, objPayDesignations);
                IsDirty = objPaySalaryEditingDA.IsDirty;
                if (IsDirty)
                    objConnection.Rollback();
                else
                    objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return updatedCount;
        }
        public int Insert(List<PaySalaryEditingDC> objPayDesignations)
        {
            int insertedCount = 0;
            DBConnection objConnection = new DBConnection();
            PaySalaryEditingDA objPaySalaryEditingDA = new PaySalaryEditingDA();
            try
            {
                objConnection.Open(true);
                insertedCount = objPaySalaryEditingDA.Insert(objConnection, objPayDesignations);
                objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return insertedCount;
        }
        public int Delete(List<PaySalaryEditingDC> objPayDesignations)
        {
            int deletedCount = 0;
            DBConnection objConnection = new DBConnection();
            PaySalaryEditingDA objPaySalaryEditingDA = new PaySalaryEditingDA();
            try
            {
                objConnection.Open(true);
                deletedCount = objPaySalaryEditingDA.Delete(objConnection, objPayDesignations);
                objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return deletedCount;
        }


    }
}
