
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 10/6/2018 12:16:07 AM
// Last Updated on: 

using System;
using System.Collections.Generic;
using EPay.DataClasses;
using EPay.DataAccess;

namespace EPay.BusinessLayer
{		
	public class RoleBL
	{
		public bool IsDirty { get; set; }
		
		public List<RoleDC>  LoadAll()
		{
			DBConnection objConnection = new DBConnection();
			RoleDA objRoleDA = new RoleDA();
			List<RoleDC>  objRoleDC = null;
            try
            {
				objConnection.Open(false);
				objRoleDC = objRoleDA.LoadAll(objConnection);
            }
            catch (Exception ex)
            {
                throw ex;
            }   
			finally 
            {
                objConnection.Close();
            }
            return objRoleDC;
		}
		
		
		public RoleDC LoadByPrimaryKey(string RoleID)
		{
			DBConnection objConnection = new DBConnection();
			RoleDA objRoleDA = new RoleDA();
			RoleDC objRoleDC = null;
            try
            {
				objConnection.Open(false);
				objRoleDC = objRoleDA.LoadByPrimaryKey(objConnection, RoleID);                
            }
            catch (Exception ex)
            {
                throw ex;
            }   
			finally 
            {
                objConnection.Close();
            }
            return objRoleDC;
		}
		public int Update(List<RoleDC> objRoles)        
        {
            int updatedCount = 0;
            DBConnection objConnection = new DBConnection();
            RoleDA objRoleDA = new RoleDA();
            try
            {
                objConnection.Open(true);
                updatedCount = objRoleDA.Update(objConnection, objRoles);
                IsDirty = objRoleDA.IsDirty;
                if (IsDirty)
                    objConnection.Rollback();
                else
                    objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return updatedCount;
        }
		public int Insert(List<RoleDC> objRoles)        
        {
            int insertedCount = 0;
            DBConnection objConnection = new DBConnection();
            RoleDA objRoleDA = new RoleDA();
            try
            {
                objConnection.Open(true);
                insertedCount = objRoleDA.Insert(objConnection, objRoles);
                objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return insertedCount;
        }
		public int Delete(List<RoleDC> objRoles)        
        {
            int deletedCount = 0;
            DBConnection objConnection = new DBConnection();
            RoleDA objRoleDA = new RoleDA();
            try
            {
                objConnection.Open(true);
                deletedCount = objRoleDA.Delete(objConnection, objRoles);
                objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return deletedCount;
        }	
		
		
	}
}
