
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 10/6/2018 12:16:07 AM
// Last Updated on: 

using System;
using System.Collections.Generic;
using EPay.DataClasses;
using EPay.DataAccess;

namespace EPay.BusinessLayer
{		
	public class TaskBL
	{
		public bool IsDirty { get; set; }
		
		public List<TaskDC>  LoadAll()
		{
			DBConnection objConnection = new DBConnection();
			TaskDA objTaskDA = new TaskDA();
			List<TaskDC>  objTaskDC = null;
            try
            {
				objConnection.Open(false);
				objTaskDC = objTaskDA.LoadAll(objConnection);
            }
            catch (Exception ex)
            {
                throw ex;
            }   
			finally 
            {
                objConnection.Close();
            }
            return objTaskDC;
		}
		
		
		public TaskDC LoadByPrimaryKey(string TaskID)
		{
			DBConnection objConnection = new DBConnection();
			TaskDA objTaskDA = new TaskDA();
			TaskDC objTaskDC = null;
            try
            {
				objConnection.Open(false);
				objTaskDC = objTaskDA.LoadByPrimaryKey(objConnection, TaskID);                
            }
            catch (Exception ex)
            {
                throw ex;
            }   
			finally 
            {
                objConnection.Close();
            }
            return objTaskDC;
		}
		public int Update(List<TaskDC> objTasks)        
        {
            int updatedCount = 0;
            DBConnection objConnection = new DBConnection();
            TaskDA objTaskDA = new TaskDA();
            try
            {
                objConnection.Open(true);
                updatedCount = objTaskDA.Update(objConnection, objTasks);
                IsDirty = objTaskDA.IsDirty;
                if (IsDirty)
                    objConnection.Rollback();
                else
                    objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return updatedCount;
        }
		public int Insert(List<TaskDC> objTasks)        
        {
            int insertedCount = 0;
            DBConnection objConnection = new DBConnection();
            TaskDA objTaskDA = new TaskDA();
            try
            {
                objConnection.Open(true);
                insertedCount = objTaskDA.Insert(objConnection, objTasks);
                objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return insertedCount;
        }
		public int Delete(List<TaskDC> objTasks)        
        {
            int deletedCount = 0;
            DBConnection objConnection = new DBConnection();
            TaskDA objTaskDA = new TaskDA();
            try
            {
                objConnection.Open(true);
                deletedCount = objTaskDA.Delete(objConnection, objTasks);
                objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return deletedCount;
        }	
		
		
	}
}
