
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/6/2017 2:43:00 PM
// Last Updated on: 

using System;
namespace EPay.DataClasses
{		
	public partial class DAILYDC
    {
        #region Job/Uknown Daily Data
        public string JOB_FILE_NUMBER { get; set; }
        public string CLIENT_PM { get; set; }
        public int CLIENT { get; set; }
        public string CLIENT_NAME { get; set; }
        public string NODE_ID1 { get; set; }
        public string NODE_ID2 { get; set; }
        public string NODE_ID3 { get; set; }
        public string HUB { get; set; }
        public int? HYLAN_PM { get; set; }
        public string HYLAN_PM_NAME { get; set; }
        public string STREET_ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string LAT { get; set; }
        public string LONG { get; set; }
        public string POLE_LOCATION { get; set; }
        #endregion

        public string DAILY_TYPE_NAME { get; set; }
        public string DAILY_STATUS_NAME { get; set; }
        public string DAILY_SHIFT_NAME { get; set; }

        public string HYLAN_PROJECT_ID { get; set; }

        public int DU_DAILY_ID { get; set; }

        private POST_MESSAGEDC m_POST_MESSAGEDC = new POST_MESSAGEDC();
        public bool HasChanges { get; set; }
        public POST_MESSAGEDC POST_MESSAGEDC
        {
            get { return m_POST_MESSAGEDC; }
            set { m_POST_MESSAGEDC = value; }
        }

        public int MP_COUNT { get; set; }
        public int MV_COUNT { get; set; }
        public int LV_COUNT { get; set; }
        public int VV_COUNT { get; set; }
        public int WV_COUNT { get; set; }
        public int AR_COUNT { get; set; }
        public int MDU_COUNT { get; set; }
        public decimal TRACK_REVENUE { get; set; }
        public int ATTACHMENTS_COUNT { get; set; }
        public string CREATED_BY_NAME { get; set; }
        public bool TRANSACTION_SUCCESS { get; set; }
        public string MODIFIED_BY_NAME { get; set; }
        public string MODIFIED_ON1 { get; set; }

    }
}
