
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/8/2017 3:17:49 PM
// Last Updated on: 

using System;
namespace EPay.DataClasses
{		
	public partial class DAILY_UNKNOWNDC
	{
        private POST_MESSAGEDC m_POST_MESSAGEDC = new POST_MESSAGEDC();
        public bool HasChanges { get; set; }
        public POST_MESSAGEDC POST_MESSAGEDC
        {
            get { return m_POST_MESSAGEDC; }
            set { m_POST_MESSAGEDC = value; }
        }

        public string MODIFIED_BY_NAME { get; set; }
    }
}
