
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/6/2017 2:43:00 PM
// Last Updated on: 

using System;
namespace EPay.DataClasses
{		
	public partial class MAN_POWERDC
    {
        private POST_MESSAGEDC m_POST_MESSAGEDC = new POST_MESSAGEDC();
        public bool HasChanges { get; set; }
        public POST_MESSAGEDC POST_MESSAGEDC
        {
            get { return m_POST_MESSAGEDC; }
            set { m_POST_MESSAGEDC = value; }
        }
    }
}
