
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 2/23/2017 3:04:28 PM
// Last Updated on: 

using System;
namespace NMART.DataClasses
{
    [Serializable]
    public class DAILY_ATTACHMENTDC
    {
        public int DAILY_ID { get; set; }
        public int ATTACHMENT_ID { get; set; }
        public bool IsDirty { get; set; }
    }
}
