
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/6/2017 2:43:00 PM
// Last Updated on: 

using System;
namespace EPay.DataClasses
{		
	public partial class DAILYDC : AbstractDataClass
    {	
 		public int DAILY_ID { get; set; }
 		public int? PROJECT_ID { get; set; }
 		public int? JOB_ID { get; set; }
 		public int DAILY_TYPE { get; set; }
 		public DateTime DAILY_DATE { get; set; }
 		public string DAY_OF_WEEK { get; set; }
        public string FOREMAN { get; set; }
        public string HYLAN_JOB_NUMBER { get; set; }
        public int DAILY_DAYS { get; set; }
 		public int STATUS { get; set; }
 		public int SHIFT { get; set; }
 		public string WORK_ORDER_NUMBER { get; set; }
 		public string DAILY_TYPE_NOTES { get; set; }
        public string QUICK_NOTES { get; set; }
        public DateTime CREATED_ON { get; set; }
 		public int CREATED_BY { get; set; }
 		public DateTime MODIFIED_ON { get; set; }
 		public int MODIFIED_BY { get; set; }
 		public int LOCK_COUNTER { get; set; }
 		public bool IsDirty { get; set; }
	}
}
