
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/8/2017 3:17:49 PM
// Last Updated on: 

using System;
namespace EPay.DataClasses
{		
	public partial class DAILY_UNKNOWNDC : AbstractDataClass
    {	
 		public int DU_DAILY_ID { get; set; }
 		public int DAILY_ID { get; set; }
 		public string NODE_ID1 { get; set; }
 		public string NODE_ID2 { get; set; }
 		public string NODE_ID3 { get; set; }
 		public string HUB { get; set; }
 		public int? HYLAN_PM { get; set; }
 		public string STREET_ADDRESS { get; set; }
 		public string CITY { get; set; }
 		public string STATE { get; set; }
 		public string ZIP { get; set; }
 		public string LAT { get; set; }
 		public string LONG { get; set; }
 		public string POLE_LOCATION { get; set; }
 		public string CLIENT_PM { get; set; }
 		public int UNKNOWN_STATUS { get; set; }
 		public DateTime CREATED_ON { get; set; }
 		public int CREATED_BY { get; set; }
 		public DateTime MODIFIED_ON { get; set; }
 		public int MODIFIED_BY { get; set; }
 		public int LOCK_COUNTER { get; set; }
 		public bool IsDirty { get; set; }
	}
}
