
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/19/2015 3:47:53 PM
// Last Updated on: 

using System;
namespace EPay.DataClasses
{

    public partial class EXCEPTIONDC 
	{	
 		public int FIELD_ID { get; set; }
        public string EXCEPTION_MESSAGE { get; set; } 	
        public string STACK_TRACK { get; set; }	
	}
}
