
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/19/2015 3:47:53 PM
// Last Updated on: 

using System;
namespace EPay.DataClasses
{

    public class LOOK_UPDC : AbstractDataClass
	{	
 		public int LOOK_UP_ID { get; set; }
 		public string LU_NAME { get; set; }
 		public string LU_TYPE { get; set; }
 		public bool IsDirty { get; set; }
	}
}
