
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 5/2/2015 5:36:52 PM
// Last Updated on: 

using System;
namespace EPay.DataClasses
{
    public partial class MESSAGEDC : AbstractDataClass
	{	
 		public int MESSAGE_ID { get; set; }
 		public int EVENT_ID { get; set; }
 		public int PURPOSE_ID { get; set; }
 		public int DELIVERY_METHOD_ID { get; set; }
 		public DateTime? CALL_ON { get; set; }
 		public string ACCESS_CODE { get; set; }
 		public string SUBJECT { get; set; }
 		public string CONTENTS { get; set; }
 		public string RECIPIENTS { get; set; }
 		public DateTime CREATED_ON { get; set; }
 		public int CREATED_BY { get; set; }
 		public int? LOCK_COUNTER { get; set; }
 		public bool IsDirty { get; set; }
	}
}
