
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/19/2015 3:47:53 PM
// Last Updated on: 

using System;
namespace EPay.DataClasses
{

    public partial class PERMITDC : AbstractDataClass
	{
        public int PERMIT_ID { get; set; }
        public int? PROJECT_ID { get; set; }
        public int? JOB_ID { get; set; }
        public string CLIENT { get; set; }
        public string NODE_ID1 { get; set; }
        public string NODE_ID2 { get; set; }
        public string NODE_ID3 { get; set; }
        public string HUB { get; set; }
        public int? HYLAN_PM { get; set; }
        public string STREET_ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string LAT { get; set; }
        public string LONG { get; set; }
        public string POLE_LOCATION { get; set; }
        public string PERMIT_NUMBER_TEXT { get; set; }
        public string PERMIT_TYPE { get; set; }
        public string DOT_TRACKING_NUMBER { get; set; }
        public string SEGMENT { get; set; }
        public string IS_PROTECTED_STREET { get; set; }
        public DateTime? MARKOUT_START_DATE { get; set; }
        public DateTime? MARKOUT_END_DATE { get; set; }
        public bool STIPULATION_DAY { get; set; }
        public bool STIPULATION_NIGHT { get; set; }
        public bool STIPULATION_WEEKEND { get; set; }
        public string STIPULATIONS_OTHER { get; set; }
        public DateTime? ISSUED_DATE { get; set; }
        public DateTime? VALID_DATE { get; set; }
        public DateTime? EXPIRES_DATE { get; set; }
        public int? PERMIT_STATUS { get; set; }
        public string NOTES { get; set; }        
        public DateTime? REJECTED_DATE { get; set; }
        public int? REJECTED_REASON { get; set; }
        public int CREATED_BY { get; set; }
        public DateTime CREATED_ON { get; set; }
        public int MODIFIED_BY { get; set; }
        public DateTime MODIFIED_ON { get; set; }
        public int LOCK_COUNTER { get; set; }
        public bool IsDirty { get; set; }
        public DateTime? SUBMITTED_DATE { get; set; }
        public bool IS_PAGE2_FILLED { get; set; }

    }
}
