
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/19/2015 3:47:53 PM
// Last Updated on: 

using System;
namespace EPay.DataClasses
{

    public class SCREENDC : AbstractDataClass
	{	
 		public int SCREEN_ID { get; set; }
 		public string SCREEN_NAME { get; set; }
 		public DateTime CREATED_ON { get; set; }
 		public int CREATED_BY { get; set; }
 		public DateTime MODIFIED_ON { get; set; }
 		public int MODIFIED_BY { get; set; }
        public bool IS_EVENT_BASED { get; set; }
 		public bool IsDirty { get; set; }
	}
}
