
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/19/2015 3:47:53 PM
// Last Updated on: 

using System;
namespace EPay.DataClasses
{

    public partial class USERS_COMPANIEDC : AbstractDataClass
	{	
 		public int USER_ID { get; set; }
 		public int COMPANY_ID { get; set; }
 		public bool IsDirty { get; set; }
	}
}
