
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/19/2015 3:47:53 PM
// Last Updated on: 

using System;
namespace EPay.DataClasses
{

    public class USERS_RMAGDC : AbstractDataClass
	{	
 		public int USER_RMAG_ID { get; set; }
 		public int USER_ID { get; set; }
 		public int RMAG_ID { get; set; }
 		public DateTime CREATED_ON { get; set; }
 		public int CREATED_BY { get; set; }
 		public DateTime MODIFIED_ON { get; set; }
 		public int MODIFIED_BY { get; set; }
 		public bool IsDirty { get; set; }
	}
}
