
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/6/2017 2:32:25 PM
// Last Updated on: 

using System;
using System.Collections.Generic;
using EPay.DataClasses;
using EPay.DataAccess;

namespace EPay.BusinessLayer
{		
	public class MATERIALBL
	{
		public bool IsDirty { get; set; }
		
		public List<MATERIALDC>  LoadAll()
		{
			DBConnection objConnection = new DBConnection();
			MATERIALDA objMATERIAL_VALUDA = new MATERIALDA();
			List<MATERIALDC>  objMATERIAL_VALUDC = null;
            try
            {
				objConnection.Open(false);
				objMATERIAL_VALUDC = objMATERIAL_VALUDA.LoadAll(objConnection);
            }
            catch (Exception ex)
            {
                throw ex;
            }   
			finally 
            {
                objConnection.Close();
            }
            return objMATERIAL_VALUDC;
		}
		
		
		public MATERIALDC LoadByPrimaryKey(int MATERIAL_VALUE_ID)
		{
			DBConnection objConnection = new DBConnection();
			MATERIALDA objMATERIAL_VALUDA = new MATERIALDA();
			MATERIALDC objMATERIAL_VALUDC = null;
            try
            {
				objConnection.Open(false);
				objMATERIAL_VALUDC = objMATERIAL_VALUDA.LoadByPrimaryKey(objConnection, MATERIAL_VALUE_ID);                
            }
            catch (Exception ex)
            {
                throw ex;
            }   
			finally 
            {
                objConnection.Close();
            }
            return objMATERIAL_VALUDC;
		}
        public List<MATERIALDC> LoadByDailyIDAndType(int DAILY_ID, int DAILY_TYPE, int SUB_CATEGORY)
        {
            DBConnection objConnection = new DBConnection();
            MATERIALDA objMATERIAL_VALUDA = new MATERIALDA();
            List<MATERIALDC> objMATERIAL_VALUDC = null;
            try
            {
                objConnection.Open(false);
                objMATERIAL_VALUDC = objMATERIAL_VALUDA.LoadByDailyIDAndType(objConnection, DAILY_ID, DAILY_TYPE, SUB_CATEGORY);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return objMATERIAL_VALUDC;
        }
        public int Update(DBConnection objConnection, MATERIALDC objMATERIAL_VALUs)        
        {
            int updatedCount = 0;
            MATERIALDA objMATERIAL_VALUDA = new MATERIALDA();
            updatedCount = objMATERIAL_VALUDA.Update(objConnection, objMATERIAL_VALUs);
            return updatedCount;
        }
		public int Insert(DBConnection objConnection, MATERIALDC objMATERIAL_VALUs)        
        {
            int insertedCount = 0;
            MATERIALDA objMATERIAL_VALUDA = new MATERIALDA();
            insertedCount = objMATERIAL_VALUDA.Insert(objConnection, objMATERIAL_VALUs);
            return insertedCount;
        }
		public int Delete(List<MATERIALDC> objMATERIAL_VALUs)        
        {
            int deletedCount = 0;
            DBConnection objConnection = new DBConnection();
            MATERIALDA objMATERIAL_VALUDA = new MATERIALDA();
            try
            {
                objConnection.Open(true);
                deletedCount = objMATERIAL_VALUDA.Delete(objConnection, objMATERIAL_VALUs);
                objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return deletedCount;
        }	
		
		
	}
}
