
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/20/2015 7:25:12 PM
// Last Updated on: 

using System;
using System.Collections.Generic;
using EPay.DataClasses;
using EPay.DataAccess;

namespace EPay.BusinessLayer
{		
	public partial class USERS_COMPANIEBL
	{

        public USERS_COMPANIEDC LoadByUserID(int USER_ID, string accessType)
        {
            DBConnection objConnection = new DBConnection();
            USERS_COMPANIEDA objUSERS_COMPANIEDA = new USERS_COMPANIEDA();
            USERS_COMPANIEDC objUSERS_COMPANIEDC = null;
            try
            {
                objConnection.Open(false);
                objUSERS_COMPANIEDC = objUSERS_COMPANIEDA.LoadByUserID(USER_ID, accessType, objConnection);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return objUSERS_COMPANIEDC;
        }
        public int CheckCompanyAssociation(int CompanyID)
        {
            DBConnection objConnection = new DBConnection();
            USERS_COMPANIEDA objUSERS_COMPANIEDA = new USERS_COMPANIEDA();
            int rowCount = 0;
           
            try
            {
                objConnection.Open(false);
                rowCount = objUSERS_COMPANIEDA.CheckCompanyAssociation(CompanyID, objConnection);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return rowCount;
        }
		
	}
}
