
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 10/6/2018 12:17:32 AM
// Last Updated on: 

using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using Microsoft.Practices.EnterpriseLibrary.Data;
using EPay.DataClasses;
namespace EPay.DataAccess
{		
	public class TaskDA
	{
		public bool IsDirty {get; set;}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public List<TaskDC> LoadAll(DBConnection Connection)
		{
			List<TaskDC> objTask = new List<TaskDC>();
			StringBuilder sql = new StringBuilder();
			sql.Append("proc_TasksLoadAll");

			DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
 
 
            DataSet ds = new DataSet();
			
			if (Connection.Transaction != null)
				ds = Connection.dataBase.ExecuteDataSet(dbCommandWrapper.DBCommand, Connection.Transaction);
			else
				ds = Connection.dataBase.ExecuteDataSet(dbCommandWrapper.DBCommand);
			
			  foreach (DataRow drRow in ds.Tables[0].Rows)
                {
				objTask.Add(FillObject(drRow));
				}
				
            return objTask;
		}
		
		public TaskDC LoadByPrimaryKey(DBConnection Connection, string TaskID)
		{
			TaskDC objTask = new TaskDC();
			StringBuilder sql = new StringBuilder();
			sql.Append("proc_TasksLoadByPrimaryKey");

			DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
						dbCommandWrapper.AddInParameter("p_TaskID", DbType.String, TaskID);
 				

			IDataReader reader = null;

			if (Connection.Transaction != null)
				reader = Connection.dataBase.ExecuteReader(dbCommandWrapper.DBCommand, Connection.Transaction);
			else
				reader = Connection.dataBase.ExecuteReader(dbCommandWrapper.DBCommand);

			objTask = FillObject(reader);
            return objTask;
		}
		public int Update(DBConnection Connection, List<TaskDC> objTasks)        
        {
            int updatedCount = 0;
            foreach (TaskDC objTask in objTasks)
            {
                updatedCount = Update(Connection, objTask);
            }
            return updatedCount;
        }
		private int Update(DBConnection Connection, TaskDC objTask)
        {
            int updateCount = 0;

            StringBuilder sql = new StringBuilder();
            sql.Append("proc_TasksUpdate");

            DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
			
            
			dbCommandWrapper.AddInParameter("p_TaskID", DbType.String, objTask.TaskID);
			dbCommandWrapper.AddInParameter("p_TaskDescription", DbType.String, objTask.TaskDescription);
			dbCommandWrapper.AddInParameter("p_SerialNo", DbType.Int32, objTask.SerialNo);
			dbCommandWrapper.AddInParameter("p_CanView", DbType.Boolean, objTask.CanView);
			dbCommandWrapper.AddInParameter("p_CanAdd", DbType.Boolean, objTask.CanAdd);
			dbCommandWrapper.AddInParameter("p_CanEdit", DbType.Boolean, objTask.CanEdit);
			dbCommandWrapper.AddInParameter("p_CanDelete", DbType.Boolean, objTask.CanDelete);
			dbCommandWrapper.AddInParameter("p_CanPrint", DbType.Boolean, objTask.CanPrint);
			dbCommandWrapper.AddInParameter("p_IsSyncReq", DbType.Boolean, objTask.IsSyncReq);
			dbCommandWrapper.AddInParameter("p_IsSync", DbType.Boolean, objTask.IsSync);
			dbCommandWrapper.AddInParameter("p_RowState", DbType.String, objTask.RowState);
			dbCommandWrapper.AddInParameter("p_AddOn", DbType.DateTime, objTask.AddOn);
			dbCommandWrapper.AddInParameter("p_AddBy", DbType.String, objTask.AddBy);
			dbCommandWrapper.AddInParameter("p_EditOn", DbType.DateTime, objTask.EditOn);
			dbCommandWrapper.AddInParameter("p_EditBy", DbType.String, objTask.EditBy);
			dbCommandWrapper.AddInParameter("p_SyncDate", DbType.DateTime, objTask.SyncDate);
			dbCommandWrapper.AddInParameter("p_CompanyID", DbType.Int32, objTask.CompanyID);


            if (Connection.Transaction != null)
                updateCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                updateCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand);
			
			if (updateCount == 0)
                objTask.IsDirty = IsDirty = true;
            
			return updateCount;
        }
		public int Insert(DBConnection Connection, List<TaskDC> objTasks)        
        {
            int insertCount = 0;
            foreach (TaskDC objTask in objTasks)
            {
                 insertCount = Insert(Connection, objTask);
            }
            return  insertCount;
        }
		private int Insert(DBConnection Connection, TaskDC objTask)
        {
            int insertCount = 0;

            StringBuilder sql = new StringBuilder();
            sql.Append("proc_TasksInsert");

            DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
			
            
			dbCommandWrapper.AddInParameter("p_TaskID", DbType.String, objTask.TaskID);
			dbCommandWrapper.AddInParameter("p_TaskDescription", DbType.String, objTask.TaskDescription);
			dbCommandWrapper.AddInParameter("p_SerialNo", DbType.Int32, objTask.SerialNo);
			dbCommandWrapper.AddInParameter("p_CanView", DbType.Boolean, objTask.CanView);
			dbCommandWrapper.AddInParameter("p_CanAdd", DbType.Boolean, objTask.CanAdd);
			dbCommandWrapper.AddInParameter("p_CanEdit", DbType.Boolean, objTask.CanEdit);
			dbCommandWrapper.AddInParameter("p_CanDelete", DbType.Boolean, objTask.CanDelete);
			dbCommandWrapper.AddInParameter("p_CanPrint", DbType.Boolean, objTask.CanPrint);
			dbCommandWrapper.AddInParameter("p_IsSyncReq", DbType.Boolean, objTask.IsSyncReq);
			dbCommandWrapper.AddInParameter("p_IsSync", DbType.Boolean, objTask.IsSync);
			dbCommandWrapper.AddInParameter("p_RowState", DbType.String, objTask.RowState);
			dbCommandWrapper.AddInParameter("p_AddOn", DbType.DateTime, objTask.AddOn);
			dbCommandWrapper.AddInParameter("p_AddBy", DbType.String, objTask.AddBy);
			dbCommandWrapper.AddInParameter("p_EditOn", DbType.DateTime, objTask.EditOn);
			dbCommandWrapper.AddInParameter("p_EditBy", DbType.String, objTask.EditBy);
			dbCommandWrapper.AddInParameter("p_SyncDate", DbType.DateTime, objTask.SyncDate);
			dbCommandWrapper.AddInParameter("p_CompanyID", DbType.Int32, objTask.CompanyID);


            if (Connection.Transaction != null)
                insertCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                insertCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand);

            return insertCount;
        }
		public int Delete(DBConnection Connection, List<TaskDC> objTasks)        
        {
            int deleteCount = 0;
            foreach (TaskDC objTask in objTasks)
            {
                 deleteCount = Delete(Connection, objTask);
            }
            return  deleteCount;
        }
		private int Delete(DBConnection Connection, TaskDC objTask)
        {
            int deleteCount = 0;

            StringBuilder sql = new StringBuilder();
            sql.Append("proc_TasksDelete");

            DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
            
			dbCommandWrapper.AddInParameter("p_TaskID", DbType.String, objTask.TaskID);

            if (Connection.Transaction != null)
                deleteCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                deleteCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand);

            return deleteCount;
        }
		private TaskDC FillObject(IDataReader reader)
        {
			TaskDC objTask = null;
            if (reader != null && reader.Read())
            {	
				objTask = new TaskDC();
				objTask.TaskID = (String)reader["TaskID"];
				objTask.TaskDescription = (String)reader["TaskDescription"];
				objTask.SerialNo = (int)reader["SerialNo"];
				objTask.CanView = (Boolean)reader["CanView"];
				objTask.CanAdd = (Boolean)reader["CanAdd"];
				objTask.CanEdit = (Boolean)reader["CanEdit"];
				objTask.CanDelete = (Boolean)reader["CanDelete"];
				objTask.CanPrint = (Boolean)reader["CanPrint"];
				objTask.IsSyncReq = (Boolean)reader["IsSyncReq"];
				objTask.IsSync = (Boolean)reader["IsSync"];
				objTask.RowState =(String) reader["RowState"];
				objTask.AddOn = reader["AddOn"] == DBNull.Value ? null : (DateTime?)reader["AddOn"];
				objTask.AddBy = (String)reader["AddBy"];
				objTask.EditOn = reader["EditOn"] == DBNull.Value ? null : (DateTime?)reader["EditOn"];
				objTask.EditBy = (String)reader["EditBy"];
				objTask.SyncDate = reader["SyncDate"] == DBNull.Value ? null : (DateTime?)reader["SyncDate"];
				objTask.CompanyID = reader["CompanyID"] == DBNull.Value ? null : (int?)reader["CompanyID"];

                reader.Close();
                reader.Dispose();
            }
            return objTask;
        }
		private TaskDC FillObject(DataRow row)
        {
			TaskDC objTask = null;
			objTask = new TaskDC();
			objTask.TaskID = (String)row["TaskID"];
			objTask.TaskDescription = (String)row["TaskDescription"];
			objTask.SerialNo = (int)row["SerialNo"];
			objTask.CanView = (Boolean)row["CanView"];
			objTask.CanAdd = (Boolean)row["CanAdd"];
			objTask.CanEdit = (Boolean)row["CanEdit"];
			objTask.CanDelete = (Boolean)row["CanDelete"];
			objTask.CanPrint = (Boolean)row["CanPrint"];
			objTask.IsSyncReq = (Boolean)row["IsSyncReq"];
			objTask.IsSync = (Boolean)row["IsSync"];
			objTask.RowState = (string)row["RowState"];
			objTask.AddOn = row["AddOn"] == DBNull.Value ? null : (DateTime?)row["AddOn"];
			objTask.AddBy = (String)row["AddBy"];
			objTask.EditOn = row["EditOn"] == DBNull.Value ? null : (DateTime?)row["EditOn"];
			objTask.EditBy =(String) row["EditBy"];
			objTask.SyncDate = row["SyncDate"] == DBNull.Value ? null : (DateTime?)row["SyncDate"];
			objTask.CompanyID = row["CompanyID"] == DBNull.Value ? null : (int?)row["CompanyID"];

            return objTask;
        }
	}
}
