
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/20/2015 7:25:12 PM
// Last Updated on: 

using System;
using System.Collections.Generic;
using EPay.DataClasses;
using EPay.DataAccess;

namespace EPay.BusinessLayer
{		
	public class SCREENBL
	{
		public bool IsDirty { get; set; }
		
		public List<SCREENDC>  LoadAll()
		{
			DBConnection objConnection = new DBConnection();
			SCREENDA objSCREENDA = new SCREENDA();
			List<SCREENDC>  objSCREENDC = null;
            try
            {
				objConnection.Open(false);
				objSCREENDC = objSCREENDA.LoadAll(objConnection);
            }
            catch (Exception ex)
            {
                throw ex;
            }   
			finally 
            {
                objConnection.Close();
            }
            return objSCREENDC;
		}
		
		
		public SCREENDC LoadByPrimaryKey(int SCREEN_ID)
		{
			DBConnection objConnection = new DBConnection();
			SCREENDA objSCREENDA = new SCREENDA();
			SCREENDC objSCREENDC = null;
            try
            {
				objConnection.Open(false);
				objSCREENDC = objSCREENDA.LoadByPrimaryKey(objConnection, SCREEN_ID);                
            }
            catch (Exception ex)
            {
                throw ex;
            }   
			finally 
            {
                objConnection.Close();
            }
            return objSCREENDC;
		}
		public int Update(List<SCREENDC> objSCREENs)        
        {
            int updatedCount = 0;
            DBConnection objConnection = new DBConnection();
            SCREENDA objSCREENDA = new SCREENDA();
            try
            {
                objConnection.Open(true);
                updatedCount = objSCREENDA.Update(objConnection, objSCREENs);
                IsDirty = objSCREENDA.IsDirty;
                if (IsDirty)
                    objConnection.Rollback();
                else
                    objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return updatedCount;
        }
		public int Insert(List<SCREENDC> objSCREENs)        
        {
            int insertedCount = 0;
            DBConnection objConnection = new DBConnection();
            SCREENDA objSCREENDA = new SCREENDA();
            try
            {
                objConnection.Open(true);
                insertedCount = objSCREENDA.Insert(objConnection, objSCREENs);
                objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return insertedCount;
        }
		public int Delete(List<SCREENDC> objSCREENs)        
        {
            int deletedCount = 0;
            DBConnection objConnection = new DBConnection();
            SCREENDA objSCREENDA = new SCREENDA();
            try
            {
                objConnection.Open(true);
                deletedCount = objSCREENDA.Delete(objConnection, objSCREENs);
                objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return deletedCount;
        }	
		
		
	}
}
