
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 4/16/2015 12:29:44 AM
// Last Updated on: 

using System;
using System.Collections.Generic;
using EPay.DataClasses;
using EPay.DataAccess;

namespace EPay.BusinessLayer
{		
	public class ST_STATE_LBL
	{
		public bool IsDirty { get; set; }
		
		public List<ST_STATE_LDC>  LoadAll()
		{
			DBConnection objConnection = new DBConnection();
			ST_STATE_LDA objST_STATE_LDA = new ST_STATE_LDA();
			List<ST_STATE_LDC>  objST_STATE_LDC = null;
            try
            {
				objConnection.Open(false);
				objST_STATE_LDC = objST_STATE_LDA.LoadAll(objConnection);
            }
            catch (Exception ex)
            {
                throw ex;
            }   
			finally 
            {
                objConnection.Close();
            }
            return objST_STATE_LDC;
		}
		
		
		public ST_STATE_LDC LoadByPrimaryKey(string ST_STATE)
		{
			DBConnection objConnection = new DBConnection();
			ST_STATE_LDA objST_STATE_LDA = new ST_STATE_LDA();
			ST_STATE_LDC objST_STATE_LDC = null;
            try
            {
				objConnection.Open(false);
				objST_STATE_LDC = objST_STATE_LDA.LoadByPrimaryKey(objConnection, ST_STATE);                
            }
            catch (Exception ex)
            {
                throw ex;
            }   
			finally 
            {
                objConnection.Close();
            }
            return objST_STATE_LDC;
		}
		public int Update(List<ST_STATE_LDC> objST_STATE_Ls)        
        {
            int updatedCount = 0;
            DBConnection objConnection = new DBConnection();
            ST_STATE_LDA objST_STATE_LDA = new ST_STATE_LDA();
            try
            {
                objConnection.Open(true);
                updatedCount = objST_STATE_LDA.Update(objConnection, objST_STATE_Ls);
                IsDirty = objST_STATE_LDA.IsDirty;
                if (IsDirty)
                    objConnection.Rollback();
                else
                    objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return updatedCount;
        }
		public int Insert(List<ST_STATE_LDC> objST_STATE_Ls)        
        {
            int insertedCount = 0;
            DBConnection objConnection = new DBConnection();
            ST_STATE_LDA objST_STATE_LDA = new ST_STATE_LDA();
            try
            {
                objConnection.Open(true);
                insertedCount = objST_STATE_LDA.Insert(objConnection, objST_STATE_Ls);
                objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return insertedCount;
        }
		public int Delete(List<ST_STATE_LDC> objST_STATE_Ls)        
        {
            int deletedCount = 0;
            DBConnection objConnection = new DBConnection();
            ST_STATE_LDA objST_STATE_LDA = new ST_STATE_LDA();
            try
            {
                objConnection.Open(true);
                deletedCount = objST_STATE_LDA.Delete(objConnection, objST_STATE_Ls);
                objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return deletedCount;
        }	
		
		
	}
}
