
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/20/2015 7:25:12 PM
// Last Updated on: 

using System;
using System.Collections.Generic;
using EPay.DataClasses;
using EPay.DataAccess;

namespace EPay.BusinessLayer
{
    public partial class USERS_COMPANIEBL
    {
        public bool IsDirty { get; set; }

        public List<USERS_COMPANIEDC> LoadAll()
        {
            DBConnection objConnection = new DBConnection();
            USERS_COMPANIEDA objUSERS_COMPANIEDA = new USERS_COMPANIEDA();
            List<USERS_COMPANIEDC> objUSERS_COMPANIEDC = null;
            try
            {
                objConnection.Open(false);
                objUSERS_COMPANIEDC = objUSERS_COMPANIEDA.LoadAll(objConnection);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return objUSERS_COMPANIEDC;
        }

        public int Insert(List<USERS_COMPANIEDC> objUSERS_COMPANIEs)
        {
            int insertedCount = 0;
            DBConnection objConnection = new DBConnection();
            USERS_COMPANIEDA objUSERS_COMPANIEDA = new USERS_COMPANIEDA();
            try
            {
                objConnection.Open(true);
                insertedCount = objUSERS_COMPANIEDA.Insert(objConnection, objUSERS_COMPANIEs);
                objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return insertedCount;
        }
    }
}
