
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/20/2015 7:25:12 PM
// Last Updated on: 

using System;
using System.Collections.Generic;
using EPay.DataClasses;
using EPay.DataAccess;

namespace EPay.BusinessLayer
{		
	public partial class USERBL
	{
		public bool IsDirty { get; set; }

      
		public USERDC LoadByPrimaryKey(int USER_ID)
		{
			DBConnection objConnection = new DBConnection();
			USERDA objUSERDA = new USERDA();
			USERDC objUSERDC = null;
            try
            {
				objConnection.Open(false);
				objUSERDC = objUSERDA.LoadByPrimaryKey(objConnection, USER_ID);                
            }
            catch (Exception ex)
            {
                throw ex;
            }   
			finally 
            {
                objConnection.Close();
            }
            return objUSERDC;
		}

		public int Delete(List<USERDC> objUSERs)        
        {
            int deletedCount = 0;
            DBConnection objConnection = new DBConnection();
            USERDA objUSERDA = new USERDA();
            try
            {
                objConnection.Open(true);
                deletedCount = objUSERDA.Delete(objConnection, objUSERs);
                objConnection.Commit();
            }
            catch (Exception ex)
            {
                objConnection.Rollback();
                throw ex;
            }
            finally
            {
                objConnection.Close();
            }
            return deletedCount;
        }	
		
		
	}
}
