
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/20/2015 7:01:27 PM
// Last Updated on: 

using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using Microsoft.Practices.EnterpriseLibrary.Data;
using EPay.DataClasses;
namespace EPay.DataAccess
{
    public partial class LOOK_UPDA
    {
        public List<LOOK_UPDC> LoadByType(string lookuptype, DBConnection Connection)
        {
            List<LOOK_UPDC> objLOOK_UP = new List<LOOK_UPDC>();
            StringBuilder sql = new StringBuilder();
            sql.Append("proc_LOOK_UPSLoadByType");

            DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
            dbCommandWrapper.AddInParameter("p_LU_TYPE", DbType.String, lookuptype);

            DataSet ds = new DataSet();

            if (Connection.Transaction != null)
                ds = Connection.dataBase.ExecuteDataSet(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                ds = Connection.dataBase.ExecuteDataSet(dbCommandWrapper.DBCommand);

            foreach (DataRow drRow in ds.Tables[0].Rows)
            {
                objLOOK_UP.Add(FillObject(drRow));
            }

            return objLOOK_UP;
        }

    }
}
