
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/6/2017 2:36:35 PM
// Last Updated on: 

using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using Microsoft.Practices.EnterpriseLibrary.Data;
using EPay.DataClasses;
using EPay.Common;

namespace EPay.DataAccess
{		
	public class MATERIALDA
	{
		public bool IsDirty {get; set;}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public List<MATERIALDC> LoadAll(DBConnection Connection)
		{
			List<MATERIALDC> objMATERIAL_VALU = new List<MATERIALDC>();
			StringBuilder sql = new StringBuilder();
			sql.Append("proc_MATERIAL_VALUELoadAll");

			DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
 
 
            DataSet ds = new DataSet();
			
			if (Connection.Transaction != null)
				ds = Connection.dataBase.ExecuteDataSet(dbCommandWrapper.DBCommand, Connection.Transaction);
			else
				ds = Connection.dataBase.ExecuteDataSet(dbCommandWrapper.DBCommand);
			
			  foreach (DataRow drRow in ds.Tables[0].Rows)
                {
				objMATERIAL_VALU.Add(FillObject(drRow));
				}
				
            return objMATERIAL_VALU;
		}
		
		public MATERIALDC LoadByPrimaryKey(DBConnection Connection, int MATERIAL_VALUE_ID)
		{
			MATERIALDC objMATERIAL_VALU = new MATERIALDC();
			StringBuilder sql = new StringBuilder();
			sql.Append("proc_MATERIAL_VALUELoadByPrimaryKey");

			DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
						dbCommandWrapper.AddInParameter("p_MATERIAL_VALUE_ID", DbType.Int32, MATERIAL_VALUE_ID);
 				

			IDataReader reader = null;

			if (Connection.Transaction != null)
				reader = Connection.dataBase.ExecuteReader(dbCommandWrapper.DBCommand, Connection.Transaction);
			else
				reader = Connection.dataBase.ExecuteReader(dbCommandWrapper.DBCommand);

			objMATERIAL_VALU = FillObject(reader);
            return objMATERIAL_VALU;
		}
        public List<MATERIALDC> LoadByDailyIDAndType(DBConnection Connection, int DAILY_ID, int DAILY_TYPE, int SUB_CATEGORY)
        {
            List<MATERIALDC> objMATERIAL_VALU = new List<MATERIALDC>();
            StringBuilder sql = new StringBuilder();
            sql.Append("proc_MATERIAL_VALUELoadByDailyIDAndType");

            DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
            dbCommandWrapper.AddInParameter("p_DAILY_ID", DbType.Int32, DAILY_ID);
            dbCommandWrapper.AddInParameter("p_DAILY_TYPE", DbType.Int32, DAILY_TYPE);
            dbCommandWrapper.AddInParameter("p_SUB_CATEGORY", DbType.Int32, SUB_CATEGORY);


            DataSet ds = new DataSet();

            if (Connection.Transaction != null)
                ds = Connection.dataBase.ExecuteDataSet(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                ds = Connection.dataBase.ExecuteDataSet(dbCommandWrapper.DBCommand);

            objMATERIAL_VALU = (Utility.ConvertToObjects<MATERIALDC>(ds.Tables[0]));


            return objMATERIAL_VALU;
        }
        public int Update(DBConnection Connection, List<MATERIALDC> objMATERIAL_VALUs)        
        {
            int updatedCount = 0;
            foreach (MATERIALDC objMATERIAL_VALU in objMATERIAL_VALUs)
            {
                updatedCount = Update(Connection, objMATERIAL_VALU);
            }
            return updatedCount;
        }
		public int Update(DBConnection Connection, MATERIALDC objMATERIAL_VALU)
        {
            int updateCount = 0;

            StringBuilder sql = new StringBuilder();
            sql.Append("proc_MATERIAL_VALUEUpdate");

            DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
			
            
			dbCommandWrapper.AddInParameter("p_MATERIAL_VALUE_ID", DbType.Int32, objMATERIAL_VALU.MATERIAL_VALUE_ID);
			dbCommandWrapper.AddInParameter("p_MATERIAL_ID", DbType.Int32, objMATERIAL_VALU.MATERIAL_ID);
			dbCommandWrapper.AddInParameter("p_DAILY_ID", DbType.Int32, objMATERIAL_VALU.DAILY_ID);
			dbCommandWrapper.AddInParameter("p_UNITS", DbType.Decimal, objMATERIAL_VALU.UNITS);
			dbCommandWrapper.AddInParameter("p_COMMENTS", DbType.String, objMATERIAL_VALU.COMMENTS);
			dbCommandWrapper.AddInParameter("p_CREATED_ON", DbType.DateTime, objMATERIAL_VALU.CREATED_ON);
			dbCommandWrapper.AddInParameter("p_CREATED_BY", DbType.Int32, objMATERIAL_VALU.CREATED_BY);
			dbCommandWrapper.AddInParameter("p_MODIFIED_ON", DbType.DateTime, objMATERIAL_VALU.MODIFIED_ON);
			dbCommandWrapper.AddInParameter("p_MODIFIED_BY", DbType.Int32, objMATERIAL_VALU.MODIFIED_BY);
			dbCommandWrapper.AddInParameter("p_LOCK_COUNTER", DbType.Int32, objMATERIAL_VALU.LOCK_COUNTER);


            if (Connection.Transaction != null)
                updateCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                updateCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand);
			
			if (updateCount == 0)
                objMATERIAL_VALU.IsDirty = IsDirty = true;
            
			return updateCount;
        }
		public int Insert(DBConnection Connection, List<MATERIALDC> objMATERIAL_VALUs)        
        {
            int insertCount = 0;
            foreach (MATERIALDC objMATERIAL_VALU in objMATERIAL_VALUs)
            {
                 insertCount = Insert(Connection, objMATERIAL_VALU);
            }
            return  insertCount;
        }
        public int Insert(DBConnection Connection, MATERIALDC objMATERIAL_VALU)
        {
            int insertCount = 0;

            StringBuilder sql = new StringBuilder();
            sql.Append("proc_MATERIAL_VALUEInsert");

            DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
			
            
			dbCommandWrapper.AddOutParameter("p_MATERIAL_VALUE_ID", DbType.Int32, objMATERIAL_VALU.MATERIAL_VALUE_ID);
			dbCommandWrapper.AddInParameter("p_MATERIAL_ID", DbType.Int32, objMATERIAL_VALU.MATERIAL_ID);
			dbCommandWrapper.AddInParameter("p_DAILY_ID", DbType.Int32, objMATERIAL_VALU.DAILY_ID);
			dbCommandWrapper.AddInParameter("p_UNITS", DbType.Decimal, objMATERIAL_VALU.UNITS);
			dbCommandWrapper.AddInParameter("p_COMMENTS", DbType.String, objMATERIAL_VALU.COMMENTS);
			dbCommandWrapper.AddInParameter("p_CREATED_ON", DbType.DateTime, objMATERIAL_VALU.CREATED_ON);
			dbCommandWrapper.AddInParameter("p_CREATED_BY", DbType.Int32, objMATERIAL_VALU.CREATED_BY);
			dbCommandWrapper.AddInParameter("p_MODIFIED_ON", DbType.DateTime, objMATERIAL_VALU.MODIFIED_ON);
			dbCommandWrapper.AddInParameter("p_MODIFIED_BY", DbType.Int32, objMATERIAL_VALU.MODIFIED_BY);
			dbCommandWrapper.AddInParameter("p_LOCK_COUNTER", DbType.Int32, objMATERIAL_VALU.LOCK_COUNTER);


            if (Connection.Transaction != null)
                insertCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                insertCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand);

            return insertCount;
        }
		public int Delete(DBConnection Connection, List<MATERIALDC> objMATERIAL_VALUs)        
        {
            int deleteCount = 0;
            foreach (MATERIALDC objMATERIAL_VALU in objMATERIAL_VALUs)
            {
                 deleteCount = Delete(Connection, objMATERIAL_VALU);
            }
            return  deleteCount;
        }
		private int Delete(DBConnection Connection, MATERIALDC objMATERIAL_VALU)
        {
            int deleteCount = 0;

            StringBuilder sql = new StringBuilder();
            sql.Append("proc_MATERIAL_VALUEDelete");

            DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
            
			dbCommandWrapper.AddInParameter("p_MATERIAL_VALUE_ID", DbType.Int32, objMATERIAL_VALU.MATERIAL_VALUE_ID);

            if (Connection.Transaction != null)
                deleteCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                deleteCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand);

            return deleteCount;
        }
		private MATERIALDC FillObject(IDataReader reader)
        {
			MATERIALDC objMATERIAL_VALU = null;
            if (reader != null && reader.Read())
            {	
				objMATERIAL_VALU = new MATERIALDC();
				objMATERIAL_VALU.MATERIAL_VALUE_ID = (int)reader["MATERIAL_VALUE_ID"];
				objMATERIAL_VALU.MATERIAL_ID = (int)reader["MATERIAL_ID"];
				objMATERIAL_VALU.DAILY_ID = (int)reader["DAILY_ID"];
				objMATERIAL_VALU.UNITS = (Decimal)reader["UNITS"];
				objMATERIAL_VALU.COMMENTS = reader["COMMENTS"] == DBNull.Value ? null : (String)reader["COMMENTS"];
				objMATERIAL_VALU.CREATED_ON = (DateTime)reader["CREATED_ON"];
				objMATERIAL_VALU.CREATED_BY = (int)reader["CREATED_BY"];
				objMATERIAL_VALU.MODIFIED_ON = (DateTime)reader["MODIFIED_ON"];
				objMATERIAL_VALU.MODIFIED_BY = (int)reader["MODIFIED_BY"];
				objMATERIAL_VALU.LOCK_COUNTER = (int)reader["LOCK_COUNTER"];

                reader.Close();
                reader.Dispose();
            }
            return objMATERIAL_VALU;
        }
		private MATERIALDC FillObject(DataRow row)
        {
			MATERIALDC objMATERIAL_VALU = null;
			objMATERIAL_VALU = new MATERIALDC();
			objMATERIAL_VALU.MATERIAL_VALUE_ID = (int)row["MATERIAL_VALUE_ID"];
			objMATERIAL_VALU.MATERIAL_ID = (int)row["MATERIAL_ID"];
			objMATERIAL_VALU.DAILY_ID = (int)row["DAILY_ID"];
			objMATERIAL_VALU.UNITS = (Decimal)row["UNITS"];
			objMATERIAL_VALU.COMMENTS = row["COMMENTS"] == DBNull.Value ? null : (String)row["COMMENTS"];
			objMATERIAL_VALU.CREATED_ON = (DateTime)row["CREATED_ON"];
			objMATERIAL_VALU.CREATED_BY = (int)row["CREATED_BY"];
			objMATERIAL_VALU.MODIFIED_ON = (DateTime)row["MODIFIED_ON"];
			objMATERIAL_VALU.MODIFIED_BY = (int)row["MODIFIED_BY"];
			objMATERIAL_VALU.LOCK_COUNTER = (int)row["LOCK_COUNTER"];

            return objMATERIAL_VALU;
        }
	}
}
