
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 1/23/2017 5:02:46 PM
// Last Updated on: 

using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using Microsoft.Practices.EnterpriseLibrary.Data;
using EPay.DataClasses;
using EPay.Common;

namespace EPay.DataAccess
{		
	public class TASK_FIBER_POWER_DIGDA : HYLAN_TASKDA
    {
		public bool IsDirty {get; set;}

        //=================================================================
        //  	public Function LoadAll() As Boolean
        //=================================================================
        //  Loads all of the records in the database, and sets the currentRow to the first row
        //=================================================================
        public override List<HYLAN_TASKDC> LoadAll(DBConnection Connection, int TASK_TITLE_ID)
		{
			List<HYLAN_TASKDC> objTASK_FIBER_POWER_DIG = new List<HYLAN_TASKDC>();
			StringBuilder sql = new StringBuilder();
			sql.Append("proc_TASK_FIBER_POWER_DIGLoadAll");

			DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
            dbCommandWrapper.AddInParameter("p_TASK_TITLE_ID", DbType.Int32, TASK_TITLE_ID);

            DataSet ds = new DataSet();

            if (Connection.Transaction != null)
                ds = Connection.dataBase.ExecuteDataSet(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                ds = Connection.dataBase.ExecuteDataSet(dbCommandWrapper.DBCommand);

            objTASK_FIBER_POWER_DIG.AddRange(Utility.ConvertToObjects<TASK_FIBER_POWER_DIGDC>(ds.Tables[0]));
            return objTASK_FIBER_POWER_DIG;
        }

        public override HYLAN_TASKDC LoadByPrimaryKey(DBConnection Connection, int TASK_TITLE_ID, int JOB_ID)
		{
			TASK_FIBER_POWER_DIGDC objTASK_FIBER_POWER_DIG = new TASK_FIBER_POWER_DIGDC();
			StringBuilder sql = new StringBuilder();
			sql.Append("proc_TASK_FIBER_POWER_DIGLoadByPrimaryKey");

			DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
            dbCommandWrapper.AddInParameter("p_JOB_ID", DbType.Int32, JOB_ID);
            dbCommandWrapper.AddInParameter("p_TASK_TITLE_ID", DbType.Int32, TASK_TITLE_ID);
            DataSet ds = new DataSet();

            if (Connection.Transaction != null)
                ds = Connection.dataBase.ExecuteDataSet(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                ds = Connection.dataBase.ExecuteDataSet(dbCommandWrapper.DBCommand);

            objTASK_FIBER_POWER_DIG = (Utility.ConvertToObject<TASK_FIBER_POWER_DIGDC>(ds.Tables[0]));
            if (ds.Tables.Count > 1)
            {
                HYLAN_TASKDC hylanTaskDC = (Utility.ConvertToObject<HYLAN_TASKDC>(ds.Tables[1]));
                objTASK_FIBER_POWER_DIG.TASK_TITLE_ID = hylanTaskDC.TASK_TITLE_ID;
                objTASK_FIBER_POWER_DIG.TASK_NAME = hylanTaskDC.TASK_NAME;
            }
            return objTASK_FIBER_POWER_DIG;
        }
        public override int Update(DBConnection Connection, List<HYLAN_TASKDC> objTASK_FIBER_POWER_DIGs)        
        {
            int updatedCount = 0;
            foreach (TASK_FIBER_POWER_DIGDC objTASK_FIBER_POWER_DIG in objTASK_FIBER_POWER_DIGs)
            {
                updatedCount = Update(Connection, objTASK_FIBER_POWER_DIG);
            }
            return updatedCount;
        }
		private int Update(DBConnection Connection, TASK_FIBER_POWER_DIGDC objTASK_FIBER_POWER_DIG)
        {
            int updateCount = 0;

            StringBuilder sql = new StringBuilder();
            sql.Append("proc_TASK_FIBER_POWER_DIGUpdate");

            DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
			
            
			dbCommandWrapper.AddInParameter("p_TASK_ID", DbType.Int32, objTASK_FIBER_POWER_DIG.TASK_ID);
			dbCommandWrapper.AddInParameter("p_JOB_ID", DbType.Int32, objTASK_FIBER_POWER_DIG.JOB_ID);
			dbCommandWrapper.AddInParameter("p_TASK_TITLE_ID", DbType.Int32, objTASK_FIBER_POWER_DIG.TASK_TITLE_ID);
			dbCommandWrapper.AddInParameter("p_REQUIRED", DbType.String, objTASK_FIBER_POWER_DIG.REQUIRED);
			dbCommandWrapper.AddInParameter("p_EST_START_DATE", DbType.DateTime, objTASK_FIBER_POWER_DIG.EST_START_DATE);
			dbCommandWrapper.AddInParameter("p_ACT_START_DATE", DbType.DateTime, objTASK_FIBER_POWER_DIG.ACT_START_DATE);
			dbCommandWrapper.AddInParameter("p_ACT_COMPLETION_DATE", DbType.DateTime, objTASK_FIBER_POWER_DIG.ACT_COMPLETION_DATE);
			dbCommandWrapper.AddInParameter("p_EST_LENGTH", DbType.Int32, objTASK_FIBER_POWER_DIG.EST_LENGTH);
			dbCommandWrapper.AddInParameter("p_ACT_LENGTH", DbType.Int32, objTASK_FIBER_POWER_DIG.ACT_LENGTH);
			dbCommandWrapper.AddInParameter("p_ON_HOLD_REASON", DbType.Int32, objTASK_FIBER_POWER_DIG.ON_HOLD_REASON);
			dbCommandWrapper.AddInParameter("p_ON_HOLD_OTHER", DbType.String, objTASK_FIBER_POWER_DIG.ON_HOLD_OTHER);
			dbCommandWrapper.AddInParameter("p_NOTES", DbType.String, objTASK_FIBER_POWER_DIG.NOTES);
			dbCommandWrapper.AddInParameter("p_FIBER_DIG_VAULT", DbType.Int32, objTASK_FIBER_POWER_DIG.FIBER_DIG_VAULT);
			dbCommandWrapper.AddInParameter("p_FIBER_DIG_TYPE", DbType.Int32, objTASK_FIBER_POWER_DIG.FIBER_DIG_TYPE);
			dbCommandWrapper.AddInParameter("p_CREATED_ON", DbType.DateTime, objTASK_FIBER_POWER_DIG.CREATED_ON);
			dbCommandWrapper.AddInParameter("p_CREATED_BY", DbType.Int32, objTASK_FIBER_POWER_DIG.CREATED_BY);
			dbCommandWrapper.AddInParameter("p_MODIFIED_ON", DbType.DateTime, objTASK_FIBER_POWER_DIG.MODIFIED_ON);
			dbCommandWrapper.AddInParameter("p_MODIFIED_BY", DbType.Int32, objTASK_FIBER_POWER_DIG.MODIFIED_BY);
			dbCommandWrapper.AddInParameter("p_LOCK_COUNTER", DbType.Int32, objTASK_FIBER_POWER_DIG.LOCK_COUNTER);


            if (Connection.Transaction != null)
                updateCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                updateCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand);
			
			if (updateCount == 0)
                objTASK_FIBER_POWER_DIG.IsDirty = IsDirty = true;
            
			return updateCount;
        }
        public override int Insert(DBConnection Connection, List<HYLAN_TASKDC> objTASK_FIBER_POWER_DIGs)        
        {
            int insertCount = 0;
            foreach (TASK_FIBER_POWER_DIGDC objTASK_FIBER_POWER_DIG in objTASK_FIBER_POWER_DIGs)
            {
                 insertCount = Insert(Connection, objTASK_FIBER_POWER_DIG);
            }
            return  insertCount;
        }
		private int Insert(DBConnection Connection, TASK_FIBER_POWER_DIGDC objTASK_FIBER_POWER_DIG)
        {
            int insertCount = 0;

            StringBuilder sql = new StringBuilder();
            sql.Append("proc_TASK_FIBER_POWER_DIGInsert");

            DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
			
            
			dbCommandWrapper.AddInParameter("p_TASK_ID", DbType.Int32, objTASK_FIBER_POWER_DIG.TASK_ID);
			dbCommandWrapper.AddInParameter("p_JOB_ID", DbType.Int32, objTASK_FIBER_POWER_DIG.JOB_ID);
			dbCommandWrapper.AddInParameter("p_TASK_TITLE_ID", DbType.Int32, objTASK_FIBER_POWER_DIG.TASK_TITLE_ID);
			dbCommandWrapper.AddInParameter("p_REQUIRED", DbType.String, objTASK_FIBER_POWER_DIG.REQUIRED);
			dbCommandWrapper.AddInParameter("p_EST_START_DATE", DbType.DateTime, objTASK_FIBER_POWER_DIG.EST_START_DATE);
			dbCommandWrapper.AddInParameter("p_ACT_START_DATE", DbType.DateTime, objTASK_FIBER_POWER_DIG.ACT_START_DATE);
			dbCommandWrapper.AddInParameter("p_ACT_COMPLETION_DATE", DbType.DateTime, objTASK_FIBER_POWER_DIG.ACT_COMPLETION_DATE);
			dbCommandWrapper.AddInParameter("p_EST_LENGTH", DbType.Int32, objTASK_FIBER_POWER_DIG.EST_LENGTH);
			dbCommandWrapper.AddInParameter("p_ACT_LENGTH", DbType.Int32, objTASK_FIBER_POWER_DIG.ACT_LENGTH);
			dbCommandWrapper.AddInParameter("p_ON_HOLD_REASON", DbType.Int32, objTASK_FIBER_POWER_DIG.ON_HOLD_REASON);
			dbCommandWrapper.AddInParameter("p_ON_HOLD_OTHER", DbType.String, objTASK_FIBER_POWER_DIG.ON_HOLD_OTHER);
			dbCommandWrapper.AddInParameter("p_NOTES", DbType.String, objTASK_FIBER_POWER_DIG.NOTES);
			dbCommandWrapper.AddInParameter("p_FIBER_DIG_VAULT", DbType.Int32, objTASK_FIBER_POWER_DIG.FIBER_DIG_VAULT);
			dbCommandWrapper.AddInParameter("p_FIBER_DIG_TYPE", DbType.Int32, objTASK_FIBER_POWER_DIG.FIBER_DIG_TYPE);
			dbCommandWrapper.AddInParameter("p_CREATED_ON", DbType.DateTime, objTASK_FIBER_POWER_DIG.CREATED_ON);
			dbCommandWrapper.AddInParameter("p_CREATED_BY", DbType.Int32, objTASK_FIBER_POWER_DIG.CREATED_BY);
			dbCommandWrapper.AddInParameter("p_MODIFIED_ON", DbType.DateTime, objTASK_FIBER_POWER_DIG.MODIFIED_ON);
			dbCommandWrapper.AddInParameter("p_MODIFIED_BY", DbType.Int32, objTASK_FIBER_POWER_DIG.MODIFIED_BY);
			dbCommandWrapper.AddInParameter("p_LOCK_COUNTER", DbType.Int32, objTASK_FIBER_POWER_DIG.LOCK_COUNTER);


            if (Connection.Transaction != null)
                insertCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                insertCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand);

            return insertCount;
        }
        public override int Delete(DBConnection Connection, List<HYLAN_TASKDC> objTASK_FIBER_POWER_DIGs)        
        {
            int deleteCount = 0;
            foreach (TASK_FIBER_POWER_DIGDC objTASK_FIBER_POWER_DIG in objTASK_FIBER_POWER_DIGs)
            {
                 deleteCount = Delete(Connection, objTASK_FIBER_POWER_DIG);
            }
            return  deleteCount;
        }
		private int Delete(DBConnection Connection, TASK_FIBER_POWER_DIGDC objTASK_FIBER_POWER_DIG)
        {
            int deleteCount = 0;

            StringBuilder sql = new StringBuilder();
            sql.Append("proc_TASK_FIBER_POWER_DIGDelete");

            DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
            
			dbCommandWrapper.AddInParameter("p_TASK_ID", DbType.Int32, objTASK_FIBER_POWER_DIG.TASK_ID);

            if (Connection.Transaction != null)
                deleteCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                deleteCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand);

            return deleteCount;
        }
		
	}
}
