
// Auto Generated by Tool Version # (1.3.0.3)
// Macrosoft Inc on: 3/6/2017 2:36:36 PM
// Last Updated on: 

using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using Microsoft.Practices.EnterpriseLibrary.Data;
using EPay.DataClasses;
using EPay.Common;

namespace EPay.DataAccess
{		
	public class WORK_DETAILDA
	{
		public bool IsDirty {get; set;}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public List<WORK_DETAILDC> LoadAll(DBConnection Connection)
		{
			List<WORK_DETAILDC> objWORK_DETAIL_VALU = new List<WORK_DETAILDC>();
			StringBuilder sql = new StringBuilder();
			sql.Append("proc_WORK_DETAIL_VALUELoadAll");

			DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
 
 
            DataSet ds = new DataSet();
			
			if (Connection.Transaction != null)
				ds = Connection.dataBase.ExecuteDataSet(dbCommandWrapper.DBCommand, Connection.Transaction);
			else
				ds = Connection.dataBase.ExecuteDataSet(dbCommandWrapper.DBCommand);
			
			  foreach (DataRow drRow in ds.Tables[0].Rows)
                {
				objWORK_DETAIL_VALU.Add(FillObject(drRow));
				}
				
            return objWORK_DETAIL_VALU;
		}
		
		public WORK_DETAILDC LoadByPrimaryKey(DBConnection Connection, int WORK_DETAIL_VALUE_ID)
		{
			WORK_DETAILDC objWORK_DETAIL_VALU = new WORK_DETAILDC();
			StringBuilder sql = new StringBuilder();
			sql.Append("proc_WORK_DETAIL_VALUELoadByPrimaryKey");

			DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
						dbCommandWrapper.AddInParameter("p_WORK_DETAIL_VALUE_ID", DbType.Int32, WORK_DETAIL_VALUE_ID);
 				

			IDataReader reader = null;

			if (Connection.Transaction != null)
				reader = Connection.dataBase.ExecuteReader(dbCommandWrapper.DBCommand, Connection.Transaction);
			else
				reader = Connection.dataBase.ExecuteReader(dbCommandWrapper.DBCommand);

			objWORK_DETAIL_VALU = FillObject(reader);
            return objWORK_DETAIL_VALU;
		}
        public List<WORK_DETAILDC> LoadByDailyIDAndType(DBConnection Connection, int DAILY_ID, int DAILY_TYPE)
        {
            List<WORK_DETAILDC> objWORK_DETAIL_VALU = new List<WORK_DETAILDC>();
            StringBuilder sql = new StringBuilder();
            sql.Append("proc_WORK_DETAIL_VALUELoadByDailyIDAndType");

            DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
            dbCommandWrapper.AddInParameter("p_DAILY_ID", DbType.Int32, DAILY_ID);
            dbCommandWrapper.AddInParameter("p_DAILY_TYPE", DbType.Int32, DAILY_TYPE);


            DataSet ds = new DataSet();

            if (Connection.Transaction != null)
                ds = Connection.dataBase.ExecuteDataSet(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                ds = Connection.dataBase.ExecuteDataSet(dbCommandWrapper.DBCommand);

            objWORK_DETAIL_VALU = (Utility.ConvertToObjects<WORK_DETAILDC>(ds.Tables[0]));


            return objWORK_DETAIL_VALU;
        }
        public int Update(DBConnection Connection, List<WORK_DETAILDC> objWORK_DETAIL_VALUs)        
        {
            int updatedCount = 0;
            foreach (WORK_DETAILDC objWORK_DETAIL_VALU in objWORK_DETAIL_VALUs)
            {
                updatedCount = Update(Connection, objWORK_DETAIL_VALU);
            }
            return updatedCount;
        }
		public int Update(DBConnection Connection, WORK_DETAILDC objWORK_DETAIL_VALU)
        {
            int updateCount = 0;

            StringBuilder sql = new StringBuilder();
            sql.Append("proc_WORK_DETAIL_VALUEUpdate");

            DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
			
            
			dbCommandWrapper.AddInParameter("p_WORK_DETAIL_VALUE_ID", DbType.Int32, objWORK_DETAIL_VALU.WORK_DETAIL_VALUE_ID);
			dbCommandWrapper.AddInParameter("p_WORK_DETAIL_ID", DbType.Int32, objWORK_DETAIL_VALU.WORK_DETAIL_ID);
			dbCommandWrapper.AddInParameter("p_DAILY_ID", DbType.Int32, objWORK_DETAIL_VALU.DAILY_ID);
			dbCommandWrapper.AddInParameter("p_PERFORMED", DbType.String, objWORK_DETAIL_VALU.PERFORMED);
			dbCommandWrapper.AddInParameter("p_UNITS", DbType.Decimal, objWORK_DETAIL_VALU.UNITS);
			dbCommandWrapper.AddInParameter("p_COMMENTS", DbType.String, objWORK_DETAIL_VALU.COMMENTS);
			dbCommandWrapper.AddInParameter("p_CREATED_ON", DbType.DateTime, objWORK_DETAIL_VALU.CREATED_ON);
			dbCommandWrapper.AddInParameter("p_CREATED_BY", DbType.Int32, objWORK_DETAIL_VALU.CREATED_BY);
			dbCommandWrapper.AddInParameter("p_MODIFIED_ON", DbType.DateTime, objWORK_DETAIL_VALU.MODIFIED_ON);
			dbCommandWrapper.AddInParameter("p_MODIFIED_BY", DbType.Int32, objWORK_DETAIL_VALU.MODIFIED_BY);
			dbCommandWrapper.AddInParameter("p_LOCK_COUNTER", DbType.Int32, objWORK_DETAIL_VALU.LOCK_COUNTER);


            if (Connection.Transaction != null)
                updateCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                updateCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand);
			
			if (updateCount == 0)
                objWORK_DETAIL_VALU.IsDirty = IsDirty = true;
            
			return updateCount;
        }
		public int Insert(DBConnection Connection, List<WORK_DETAILDC> objWORK_DETAIL_VALUs)        
        {
            int insertCount = 0;
            foreach (WORK_DETAILDC objWORK_DETAIL_VALU in objWORK_DETAIL_VALUs)
            {
                 insertCount = Insert(Connection, objWORK_DETAIL_VALU);
            }
            return  insertCount;
        }
		public int Insert(DBConnection Connection, WORK_DETAILDC objWORK_DETAIL_VALU)
        {
            int insertCount = 0;

            StringBuilder sql = new StringBuilder();
            sql.Append("proc_WORK_DETAIL_VALUEInsert");

            DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
			
            
			dbCommandWrapper.AddOutParameter("p_WORK_DETAIL_VALUE_ID", DbType.Int32, objWORK_DETAIL_VALU.WORK_DETAIL_VALUE_ID);
			dbCommandWrapper.AddInParameter("p_WORK_DETAIL_ID", DbType.Int32, objWORK_DETAIL_VALU.WORK_DETAIL_ID);
			dbCommandWrapper.AddInParameter("p_DAILY_ID", DbType.Int32, objWORK_DETAIL_VALU.DAILY_ID);
			dbCommandWrapper.AddInParameter("p_PERFORMED", DbType.String, objWORK_DETAIL_VALU.PERFORMED);
			dbCommandWrapper.AddInParameter("p_UNITS", DbType.Decimal, objWORK_DETAIL_VALU.UNITS);
			dbCommandWrapper.AddInParameter("p_COMMENTS", DbType.String, objWORK_DETAIL_VALU.COMMENTS);
			dbCommandWrapper.AddInParameter("p_CREATED_ON", DbType.DateTime, objWORK_DETAIL_VALU.CREATED_ON);
			dbCommandWrapper.AddInParameter("p_CREATED_BY", DbType.Int32, objWORK_DETAIL_VALU.CREATED_BY);
			dbCommandWrapper.AddInParameter("p_MODIFIED_ON", DbType.DateTime, objWORK_DETAIL_VALU.MODIFIED_ON);
			dbCommandWrapper.AddInParameter("p_MODIFIED_BY", DbType.Int32, objWORK_DETAIL_VALU.MODIFIED_BY);
			dbCommandWrapper.AddInParameter("p_LOCK_COUNTER", DbType.Int32, objWORK_DETAIL_VALU.LOCK_COUNTER);


            if (Connection.Transaction != null)
                insertCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                insertCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand);

            return insertCount;
        }
		public int Delete(DBConnection Connection, List<WORK_DETAILDC> objWORK_DETAIL_VALUs)        
        {
            int deleteCount = 0;
            foreach (WORK_DETAILDC objWORK_DETAIL_VALU in objWORK_DETAIL_VALUs)
            {
                 deleteCount = Delete(Connection, objWORK_DETAIL_VALU);
            }
            return  deleteCount;
        }
		private int Delete(DBConnection Connection, WORK_DETAILDC objWORK_DETAIL_VALU)
        {
            int deleteCount = 0;

            StringBuilder sql = new StringBuilder();
            sql.Append("proc_WORK_DETAIL_VALUEDelete");

            DBCommandWarpper dbCommandWrapper = new DBCommandWarpper(Connection.dataBase.GetStoredProcCommand(sql.ToString()), Connection);
            
			dbCommandWrapper.AddInParameter("p_WORK_DETAIL_VALUE_ID", DbType.Int32, objWORK_DETAIL_VALU.WORK_DETAIL_VALUE_ID);

            if (Connection.Transaction != null)
                deleteCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand, Connection.Transaction);
            else
                deleteCount = Connection.dataBase.ExecuteNonQuery(dbCommandWrapper.DBCommand);

            return deleteCount;
        }
		private WORK_DETAILDC FillObject(IDataReader reader)
        {
			WORK_DETAILDC objWORK_DETAIL_VALU = null;
            if (reader != null && reader.Read())
            {	
				objWORK_DETAIL_VALU = new WORK_DETAILDC();
				objWORK_DETAIL_VALU.WORK_DETAIL_VALUE_ID = (int)reader["WORK_DETAIL_VALUE_ID"];
				objWORK_DETAIL_VALU.WORK_DETAIL_ID = (int)reader["WORK_DETAIL_ID"];
				objWORK_DETAIL_VALU.DAILY_ID = (int)reader["DAILY_ID"];
				objWORK_DETAIL_VALU.PERFORMED = reader["PERFORMED"] == DBNull.Value ? null : (String)reader["PERFORMED"];
				objWORK_DETAIL_VALU.UNITS = (Decimal)reader["UNITS"];
				objWORK_DETAIL_VALU.COMMENTS = reader["COMMENTS"] == DBNull.Value ? null : (String)reader["COMMENTS"];
				objWORK_DETAIL_VALU.CREATED_ON = (DateTime)reader["CREATED_ON"];
				objWORK_DETAIL_VALU.CREATED_BY = (int)reader["CREATED_BY"];
				objWORK_DETAIL_VALU.MODIFIED_ON = (DateTime)reader["MODIFIED_ON"];
				objWORK_DETAIL_VALU.MODIFIED_BY = (int)reader["MODIFIED_BY"];
				objWORK_DETAIL_VALU.LOCK_COUNTER = (int)reader["LOCK_COUNTER"];

                reader.Close();
                reader.Dispose();
            }
            return objWORK_DETAIL_VALU;
        }
		private WORK_DETAILDC FillObject(DataRow row)
        {
			WORK_DETAILDC objWORK_DETAIL_VALU = null;
			objWORK_DETAIL_VALU = new WORK_DETAILDC();
			objWORK_DETAIL_VALU.WORK_DETAIL_VALUE_ID = (int)row["WORK_DETAIL_VALUE_ID"];
			objWORK_DETAIL_VALU.WORK_DETAIL_ID = (int)row["WORK_DETAIL_ID"];
			objWORK_DETAIL_VALU.DAILY_ID = (int)row["DAILY_ID"];
			objWORK_DETAIL_VALU.PERFORMED = row["PERFORMED"] == DBNull.Value ? null : (String)row["PERFORMED"];
			objWORK_DETAIL_VALU.UNITS = (Decimal)row["UNITS"];
			objWORK_DETAIL_VALU.COMMENTS = row["COMMENTS"] == DBNull.Value ? null : (String)row["COMMENTS"];
			objWORK_DETAIL_VALU.CREATED_ON = (DateTime)row["CREATED_ON"];
			objWORK_DETAIL_VALU.CREATED_BY = (int)row["CREATED_BY"];
			objWORK_DETAIL_VALU.MODIFIED_ON = (DateTime)row["MODIFIED_ON"];
			objWORK_DETAIL_VALU.MODIFIED_BY = (int)row["MODIFIED_BY"];
			objWORK_DETAIL_VALU.LOCK_COUNTER = (int)row["LOCK_COUNTER"];

            return objWORK_DETAIL_VALU;
        }
	}
}
